site_name: 生活工作-碎碎念
site_url: https://wudonghdeqiang.github.io/EPSDA/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

markdown_extensions:
  - footnotes
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed
  - attr_list
  - md_in_html

nav:
  - 首页: index.md
  - 专业随想:
      - 调度自动化主站发展历程: develop.md
      - 调度自动化主站规约-CDT: CDT.md
      - 调度自动化主站规约-101: 101.md
  - 工作实战:
      - 示例: 1.md
  - 测试验证:
      - 示例: 1.md      
  - 读书读书:
      - 示例: 1.md      
  